import { JumpCard } from './types'

export const MOCK_CARDS: JumpCard[] = [
  // Stock Cards
  {
    id: 'card-1',
    ticker: 'AAPL',
    company_name: 'Apple Inc.',
    headline: 'Apple Vision Pro demand surges after enterprise partnerships announced',
    summary: 'Apple reported a 340% quarter-over-quarter increase in Vision Pro orders following deals with Fortune 500 enterprises. Analysts are revising price targets upward on spatial computing momentum.',
    source: 'news',
    source_name: 'Bloomberg',
    bull_percent: 68,
    bear_percent: 32,
    card_type: 'stock',
    price: 213.49,
    change_percent: 2.14,
    created_at: new Date().toISOString(),
  },
  {
    id: 'card-2',
    ticker: 'NVDA',
    company_name: 'NVIDIA Corporation',
    headline: 'NVIDIA Blackwell GPU backlog extends to 18 months amid AI infrastructure buildout',
    summary: 'Hyperscalers are locked in an arms race for compute. NVDA\'s Blackwell architecture is the only game in town for frontier AI training runs. Supply constraints keeping margins elevated.',
    source: 'news',
    source_name: 'Reuters',
    bull_percent: 74,
    bear_percent: 26,
    card_type: 'stock',
    price: 875.43,
    change_percent: 3.67,
    created_at: new Date().toISOString(),
  },
  {
    id: 'card-3',
    ticker: 'TSLA',
    company_name: 'Tesla Inc.',
    headline: 'Tesla FSD v13 achieves 99.2% intervention-free miles in California trials',
    summary: 'Tesla\'s Full Self-Driving software hit a new milestone in regulatory testing. Robotaxi launch timeline moved up to Q3. Bears pointing to ongoing margin compression in core EV business.',
    source: 'news',
    source_name: 'TechCrunch',
    bull_percent: 52,
    bear_percent: 48,
    card_type: 'stock',
    price: 248.73,
    change_percent: -1.23,
    created_at: new Date().toISOString(),
  },
  {
    id: 'card-4',
    ticker: 'AMZN',
    company_name: 'Amazon.com Inc.',
    headline: 'AWS revenue accelerates to 21% YoY growth as enterprise AI adoption spikes',
    summary: 'Amazon Web Services posted its fastest growth in two years. Bedrock AI platform seeing 10x customer adoption. Retail operating margins hit all-time highs as logistics automation matures.',
    source: 'news',
    source_name: 'WSJ',
    bull_percent: 71,
    bear_percent: 29,
    card_type: 'stock',
    price: 198.12,
    change_percent: 1.87,
    created_at: new Date().toISOString(),
  },
  // Social Post Cards (Reddit style)
  {
    id: 'card-5',
    ticker: 'NVDA',
    company_name: 'NVIDIA Corporation',
    headline: 'r/wallstreetbets: NVDA $1200 by end of year or I eat my GPU',
    summary: 'DD: Every single AI company is buying Blackwell. Microsoft, Google, Meta, Amazon — they\'re ALL in. The only question is how many zeros you want on your calls. Blackwell backlog = guaranteed revenue. Valuation is high but earnings are growing faster. This isn\'t a meme. This is infrastructure.',
    source: 'reddit',
    source_name: 'u/DeepValueHunter99',
    bull_percent: 81,
    bear_percent: 19,
    card_type: 'social',
    price: 875.43,
    change_percent: 3.67,
    created_at: new Date().toISOString(),
  },
  {
    id: 'card-6',
    ticker: 'TSLA',
    company_name: 'Tesla Inc.',
    headline: 'StockTwits: TSLA is a robotics company now, stop valuing it like a car company',
    summary: 'The market is still pricing TSLA like a 2-3% margin auto manufacturer. Optimus humanoid robot is entering mass production. FSD is miles ahead of competition. EV is the floor, not the ceiling. Short thesis is completely outdated.',
    source: 'stocktwits',
    source_name: '@TeslaMaximalist',
    bull_percent: 59,
    bear_percent: 41,
    card_type: 'social',
    price: 248.73,
    change_percent: -1.23,
    created_at: new Date().toISOString(),
  },
  {
    id: 'card-7',
    ticker: 'AAPL',
    company_name: 'Apple Inc.',
    headline: 'r/stocks: Apple Services is the most underrated moat in the S&P 500',
    summary: 'People keep obsessing over iPhone units. The real story is $100B+ annual services revenue growing 15% YoY at 75% gross margins. App Store, iCloud, Apple Pay, Apple TV+ — every product funnels into recurring revenue. This is a software company wearing a hardware costume.',
    source: 'reddit',
    source_name: 'u/CompounderKing',
    bull_percent: 65,
    bear_percent: 35,
    card_type: 'social',
    price: 213.49,
    change_percent: 2.14,
    created_at: new Date().toISOString(),
  },
  // Macro News Cards
  {
    id: 'card-8',
    ticker: 'SPY',
    headline: 'Fed holds rates at 4.25-4.50%, signals two cuts in 2025 — Powell: "Watching inflation data carefully"',
    summary: 'The Federal Reserve held rates steady at their May meeting and maintained their dot plot of two 25bp cuts in 2025. Powell emphasized data dependency and pushed back on emergency cut expectations. Treasury yields fell across the curve on the news.',
    source: 'news',
    source_name: 'Federal Reserve',
    bull_percent: 61,
    bear_percent: 39,
    card_type: 'macro',
    created_at: new Date().toISOString(),
  },
  {
    id: 'card-9',
    ticker: 'OIL',
    headline: 'OPEC+ extends production cuts through Q3, Brent crude spikes 4% to $89/bbl',
    summary: 'Saudi Arabia and Russia agreed to extend voluntary production cuts of 2.2M barrels/day through September. Energy sector catching a bid. Higher oil prices historically weigh on consumer discretionary and transport sectors while benefiting energy producers.',
    source: 'news',
    source_name: 'Reuters',
    bull_percent: 44,
    bear_percent: 56,
    card_type: 'macro',
    created_at: new Date().toISOString(),
  },
  {
    id: 'card-10',
    ticker: 'GEO',
    headline: 'US-China trade tensions escalate: 60% tariffs on EVs and semiconductors proposed',
    summary: 'New trade legislation proposes sweeping tariffs on Chinese imports across EV, semiconductor, and solar sectors. Market implications span multiple sectors: US chip makers benefit, consumer electronics face headwinds, global supply chains in repricing mode.',
    source: 'news',
    source_name: 'Reuters',
    bull_percent: 38,
    bear_percent: 62,
    card_type: 'macro',
    created_at: new Date().toISOString(),
  },
]

export const MOCK_USERS = [
  { id: 'user-1', username: 'SharkFin_Capital', level: 'shark', market_score: 2847, accuracy: 73.2, total_predictions: 412 },
  { id: 'user-2', username: 'AlphaAnalyst_X', level: 'analyst', market_score: 2341, accuracy: 68.9, total_predictions: 289 },
  { id: 'user-3', username: 'MomentumMax', level: 'analyst', market_score: 1987, accuracy: 64.1, total_predictions: 198 },
  { id: 'user-4', username: 'ValueTrap_42', level: 'analyst', market_score: 1654, accuracy: 61.3, total_predictions: 156 },
  { id: 'user-5', username: 'RookieRipper', level: 'rookie', market_score: 1243, accuracy: 58.7, total_predictions: 87 },
]
